[build-system]
requires      = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "thinking-injection"
version = "0.0.1"
description = "DI framework"
readme = "README.md"
authors = [{ name = "Filip Malczak", email = "filip.malczak@gmail.com" }]
license = { file = "LICENSE" }
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development :: Libraries :: Application Frameworks",
    "Typing :: Typed"
]
keywords = ["thinking", "dependency", "injection", "di"]
dependencies = [
    "thinking-modules>=0.0.4",
    "thinking-runtime>=0.0.3",
    "bidict>=0.23.1",
    "frozendict>=2.4.4",
    "type_intersections>=0.1.1",
    "pydot>=3.0.2",
    "tinydb==4.8.2",
    "networkx==3.4.2",
    "docker==7.1.0",
    "setuptools==75.8.0", # needed by docker-py on p3.12+
    "sqlalchemy==2.0.40",
    "pymysql==1.1.1",
    "bson==0.5.10" #todo make it optional
]
requires-python = ">=3.12"

[project.urls]
Homepage = "https://github.com/FilipMalczak/thinking-injection"

[tool.setuptools]
#todo keep this up to date!!! use list_packages.py to generate it
packages = [
    "thinking_executor",
    "thinking_executor.callbacks",
    "thinking_executor.data",
    "thinking_executor_data",
    "thinking_executor_data.common",
    "thinking_executor_data.dolt",
    "thinking_executor_data.dolt.sqlalchemy",
    "thinking_injection",
    "thinking_injection.common",
    "thinking_injection.context",
    "thinking_injection.context.configurable",
    "thinking_injection.invoker",
    "thinking_injection.registry",
    "thinking_injection.registry.customizable",
    "thinking_programming",
    "thinking_reflection",
    "thinking_reflection.model",
    "thinking_services",
    "thinking_services.containers"
]
