name: CI

on: [push]


jobs:
  calculator:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
        working-directory: ./calculator
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ] # somehow windows-latest is failing; dont have time for that, *nixes work
        python-version: [
          "3.12"
        ]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install requirements
        run: |
          ./setup.sh
      - name: Run E2E tests
        run: |
          ./test.sh