name: Lint

on: [push]

permissions:
  contents: read
  checks: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install requirements
        run: |
          [ -f ./build-requirements.txt ] && pip install -r ./build-requirements.txt || echo "No build-requirements.txt found"
          [ -f ./requirements.txt ] && pip install -r ./requirements.txt || echo "No requirements.txt found"
          [ -f ./test-requirements.txt ] && pip install -r ./test-requirements.txt || echo "No test-requirements.txt found"

      - name: Run linter
        run: |
          ./run_lint.sh

      - name: Upload linter text report
        uses: actions/upload-artifact@v4
        with:
          name: lint_report.txt
          path: ./lint_report.txt

      - name: Upload linter XMLUnit report
        uses: actions/upload-artifact@v4
        with:
          name: lint_report.xml
          path: ./lint_report.xml


      - name: Publish linter report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Linter report
          path: ./lint_report.xml
          reporter: java-junit