name: On commit

on: [push]

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  ##########################################
  # TESTING OF THE FRAMEWORK
  ##########################################
  testing:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        python-version: [
          "3.12"
        ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install develop versions of thinking requirements
        if: ${{ github.ref != 'refs/heads/master' }}
        run: |
          bash ./install_develop.sh
      - name: Install requirements
        run: |
          [ -f ./build-requirements.txt ] && pip install -r ./build-requirements.txt || echo "No build-requirements.txt found"
          [ -f ./requirements.txt ] && pip install -r ./requirements.txt || echo "No requirements.txt found"
          [ -f ./test-requirements.txt ] && pip install -r ./test-requirements.txt || echo "No test-requirements.txt found"
      - name: Run tests
        run: |
          python -m test.run_all
      - name: Publish test report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Unit tests (${{matrix.os}}, ${{ matrix.python-version }}, ${{ github.event_name }})
          path: ./test_report.xml
          reporter: java-junit

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage.xml
          env_vars: OS,PYTHON
          flags: ${{matrix.os}}, ${{matrix.os}}-${{ matrix.python-version }}, ${{ matrix.python-version }}
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true

      - name: Upload XML test report
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: test_report_${{matrix.os}}__${{ matrix.python-version }}__${{ github.event_name }}.xml
          path: ./test_report.xml

      - name: Upload HTML test report
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: test_report_${{matrix.os}}__${{ matrix.python-version }}__${{ github.event_name }}.html
          path: ./test_report.html

      - name: Upload HTML coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage_${{matrix.os}}__${{ matrix.python-version }}__${{ github.event_name }}
          path: coverage/

  ##########################################
  # TESTING OF THE EXAMPLE PROJECTS
  ##########################################
  calculator:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
        working-directory: ./calculator
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest]
        python-version: [
          "3.12"
        ]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install requirements
        run: |
          ./setup.sh
      - name: Run E2E tests
        run: |
          ./test.sh
  
    calculator:
      runs-on: ${{ matrix.os }}
      defaults:
        run:
          shell: bash
          working-directory: ./clustering
      strategy:
        matrix:
          os: [ ubuntu-latest, macos-latest]
          python-version: [
            "3.12"
          ]

      steps:
        - uses: actions/checkout@v4
        - name: Set up Python ${{ matrix.python-version }}
          uses: actions/setup-python@v5
          with:
            python-version: ${{ matrix.python-version }}
        - name: Install requirements
          run: |
            ./setup.sh
        - name: Run E2E tests
          run: |
            ./test.sh
  

  ##########################################
  # LINTING OF THE WHOLE CODEBASE
  ##########################################
  linting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install requirements
        run: |
          [ -f ./build-requirements.txt ] && pip install -r ./build-requirements.txt || echo "No build-requirements.txt found"
          [ -f ./requirements.txt ] && pip install -r ./requirements.txt || echo "No requirements.txt found"
          [ -f ./test-requirements.txt ] && pip install -r ./test-requirements.txt || echo "No test-requirements.txt found"

      - name: Run linter
        run: |
          ./run_lint.sh

      - name: Upload linter text report
        uses: actions/upload-artifact@v4
        with:
          name: lint_report.txt
          path: ./lint_report.txt

      - name: Upload linter XMLUnit report
        uses: actions/upload-artifact@v4
        with:
          name: lint_report.xml
          path: ./lint_report.xml


      - name: Publish linter report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Linter report
          path: ./lint_report.xml
          reporter: java-junit
          fail-on-error: false